// flow-typed signature: 324bf99527f87406c535098c939e9444
// flow-typed version: <<STUB>>/dtz_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dtz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dtz' {
   declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dtz/bin/dtz' {
   declare module.exports: any
}

declare module 'dtz/lib/index' {
   declare module.exports: any
}

// Filename aliases
declare module 'dtz/bin/dtz.js' {
   declare module.exports: $Exports<'dtz/bin/dtz'>
}
declare module 'dtz/lib/index.js' {
   declare module.exports: $Exports<'dtz/lib/index'>
}
